---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  creationTimestamp: null
  name: gitops-role
  namespace: {{.Values.metadata.argocd_namespace}}
rules:
  - apiGroups: ["apps.open-cluster-management.io"]
    resources: ["gitopsclusters"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["placements"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
