---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  name: odf-multicluster-orchestrator
  namespace: openshift-operators
spec:
  channel: "stable-{{.Values.metadata.ocp.version}}"
  installPlanApproval: Automatic
  name: odf-multicluster-orchestrator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
