---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-gitops-odf
  namespace: policy
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipPrune, SkipDryRunOnMissingResource
    argocd.argoproj.io/sync-wave: "200"
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-gitops-odf
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  creationTimestamp: null
                  name: ocp-odf
                  namespace: openshift-gitops
                spec:
                  destination:
                    namespace: "{{.Values.metadata.argocd_app_namespace}}"
                    server: https://kubernetes.default.svc
                  project: default
                  source:
                    helm:
                      parameters:
                        - name: metadata.odf.mirroring_enabled
                          value: "true"
                    path: config/odf
                    repoURL: {{.Values.repoURL}}
                    targetRevision: {{.Values.targetRevision}}
                  syncPolicy:
                    automated:
                      prune: true
                      selfHeal: true
