apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  creationTimestamp: null
  name: gitops-app-sub-role
  namespace: busybox-sample
rules:
  - apiGroups: ["ramendr.openshift.io"]
    resources: ["drplacementcontrols"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
