---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  name: busybox
  namespace: busybox-sample
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - busybox
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
    argocd.argoproj.io/sync-wave: "100"
  name: nsgithubcom-red-hat-storage-ocm-ramen-samples
  namespace: nsgithubcom-red-hat-storage-ocm-ramen-samples-ns
spec:
  type: Git
  pathname: https://github.com/red-hat-storage/ocm-ramen-samples
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: release-{{ .Values.metadata.ocp.version }}
    apps.open-cluster-management.io/git-path: busybox-odr
    apps.open-cluster-management.io/reconcile-option: merge
    argocd.argoproj.io/sync-wave: "100"
  labels:
    app: busybox
  name: busybox-subscription-1
  namespace: busybox-sample
spec:
  channel: nsgithubcom-red-hat-storage-ocm-ramen-samples-ns/nsgithubcom-red-hat-storage-ocm-ramen-samples
  placement:
    placementRef:
      kind: PlacementRule
      name: busybox-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  labels:
    app: busybox
  name: busybox-placement-1
  namespace: busybox-sample
spec:
  clusterSelector:
    matchLabels:
      name: {{ .Values.metadata.cluster.cluster_1.name }}
