apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  creationTimestamp: null
  name: hub-cluster-role
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclusters","managedclustersets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["submariner.io"]
    resources: ["brokers"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["multicluster.odf.openshift.io"]
    resources: ["mirrorpeers"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
