---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  creationTimestamp: null
  name: {{ .Values.metadata.cluster.name_seed }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceaccount.argocd_application_controller}}
    namespace: {{.Values.metadata.argocd_namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  creationTimestamp: null
  name: {{ .Values.metadata.cluster.name_seed }}-rhacm-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:cluster-manager-admin
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceaccount.argocd_application_controller}}
    namespace: {{.Values.metadata.argocd_namespace}}
