---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  name: {{.Values.metadata.cluster.cluster_1.name}}-install-config
  namespace: {{.Values.metadata.cluster.cluster_1.name}}
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: {{ include "cluster.1.installconfig" . | b64enc}}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4
    0"
  name: {{.Values.metadata.cluster.cluster_2.name}}-install-config
  namespace: {{.Values.metadata.cluster.cluster_2.name}}
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: {{ include "cluster.2.installconfig" . | b64enc}}
type: Opaque
