---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "70"
  name: {{ .Values.metadata.cluster.cluster_1.name }}-odf
  namespace: {{ .Values.metadata.cluster.cluster_1.name }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.metadata.cluster.cluster_1.name }}
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  name: odf
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: {{ .Values.metadata.cluster.odf_worker_type }}
      zones:
      - {{ .Values.metadata.cluster.cluster_1.zone }}
  replicas: {{ .Values.metadata.cluster.odf_worker_replicas }}
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "70"
  name: {{ .Values.metadata.cluster.cluster_2.name }}-odf
  namespace: {{ .Values.metadata.cluster.cluster_2.name }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.metadata.cluster.cluster_2.name }}
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
  name: odf
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: {{ .Values.metadata.cluster.odf_worker_type }}
      zones:
      - {{ .Values.metadata.cluster.cluster_2.zone }}
  replicas: {{ .Values.metadata.cluster.odf_worker_replicas }}
  taints:
    - key: odf-only
      effect: NoSchedule
      value: "true"

