{{- range tuple .Values.metadata.cluster.cluster_1.name .Values.metadata.cluster.cluster_2.name }}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  name: submariner
  namespace: {{ . }}
spec:
  installNamespace: submariner-operator
---
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  name: submariner
  namespace: {{ . }}
spec:
  gatewayConfig:
    gateways: 1
    aws:
      instanceType: c5d.large
  IPSecNATTPort: 4500
  NATTEnable: true
  cableDriver: libreswan
  credentialsSecret:
    name: {{ . }}-aws-creds
{{- end }}

---
apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  name: submariner-broker
  namespace: {{ .Values.metadata.rhacm.clusterset }}-broker
spec:
  globalnetEnabled: false
