---
repoURL: https://github.com/nastacio/ocp-dr
targetRevision: main
serviceaccount:
  argocd_application_controller: openshift-gitops-argocd-application-controller
metadata:
  argocd_namespace: openshift-gitops
  dr:
    namespace: openshift-dr-system
  ocp:
    version: set in presync hook, based on OCP version
  odf:
    namespace: set in parent app
    storage_cluster_name: set in parent app
  rhacm:
    clusterset: set in parent app
