---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: openshift-storage-operatorgroup
  namespace: {{ .Values.metadata.odf.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.metadata.odf.namespace }}
