apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  creationTimestamp: null
  name: gitops-odf-role
  namespace: {{ .Values.metadata.odf.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["ocs.openshift.io"]
    resources: ["storageclusters"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["odf.openshift.io"]
    resources: ["storagesystems"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
