---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  creationTimestamp: null
  name: gitops-odf-dr-rb
  namespace: {{ .Values.metadata.odf.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-odf-dr-role
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceaccount.argocd_application_controller}}
    namespace: {{.Values.metadata.argocd_namespace}}
